services:
    hafas-frontend:
        container_name: hafas-frontend
        image: schmolldechsee/hafas-frontend:latest
        restart: always
        ports:
            - "4000:3000"
        networks:
            - hafas-network
        volumes:
            - .env:/app/.env
        command: [ "npm", "publish" ]

    redis:
        container_name: hafas-db
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - ./redis:/usr/local/etc/redis
            - redis-data:/data
        networks:
            - hafas-network
        command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

networks:
    hafas-network:
        external: true

volumes:
    redis-data:
        driver: local
